/**
 * Rule-based keyword tagger. No LLM.
 * Tags articles by branch and city based on keyword matching.
 */

export const BRANCH_KEYWORDS: Record<string, string[]> = {
  CSE: [
    "AI",
    "ML",
    "machine learning",
    "artificial intelligence",
    "software",
    "tech",
    "startup",
    "GPU",
    "OpenAI",
    "infosys",
    "TCS",
    "coding",
    "developer",
    "cybersecurity",
    "cloud",
    "data",
    "python",
    "javascript",
    "algorithm",
    "computer science",
    "programming",
    "deep learning",
    "neural",
    "SaaS",
    "app",
    "backend",
    "frontend",
    "fullstack",
    "DevOps",
    "kubernetes",
    "docker",
  ],
  ECE: [
    "semiconductor",
    "chip",
    "VLSI",
    "embedded",
    "IoT",
    "5G",
    "electronics",
    "circuit",
    "FPGA",
    "microcontroller",
    "Arduino",
    "Raspberry Pi",
    "signal",
    "wireless",
    "antenna",
    "PCB",
    "transistor",
    "telecom",
    "communication",
    "sensor",
    "robotics",
    "drone",
  ],
  Mechanical: [
    "manufacturing",
    "automobile",
    "EV",
    "electric vehicle",
    "CAD",
    "3D printing",
    "turbine",
    "thermal",
    "HVAC",
    "CNC",
    "machine design",
    "fluid",
    "mechanics",
    "aerospace",
    "aviation",
    "automotive",
    "engine",
    "robot",
    "automation",
    "welding",
    "casting",
  ],
  Civil: [
    "construction",
    "infrastructure",
    "bridge",
    "road",
    "highway",
    "building",
    "architecture",
    "smart city",
    "urban",
    "concrete",
    "structural",
    "irrigation",
    "dam",
    "metro",
    "railway",
    "planning",
    "real estate",
    "housing",
    "PMAY",
    "water supply",
    "sanitation",
  ],
  Electrical: [
    "power",
    "electricity",
    "renewable",
    "solar",
    "wind energy",
    "grid",
    "transformer",
    "motor",
    "inverter",
    "EV charging",
    "battery",
    "energy storage",
    "substation",
    "high voltage",
    "PLC",
    "SCADA",
    "smart grid",
    "electrification",
  ],
  MBA: [
    "business",
    "management",
    "startup",
    "funding",
    "investment",
    "VC",
    "venture capital",
    "IPO",
    "stock",
    "market",
    "strategy",
    "consulting",
    "McKinsey",
    "Deloitte",
    "BCG",
    "leadership",
    "entrepreneurship",
    "brand",
    "marketing",
    "supply chain",
    "finance",
    "fintech",
    "acquisition",
  ],
  BBA: [
    "business administration",
    "retail",
    "e-commerce",
    "logistics",
    "operations",
    "HR",
    "human resources",
    "sales",
    "customer",
    "commerce",
    "trade",
    "BBA",
    "internship",
    "corporate",
    "management trainee",
  ],
  Design: [
    "design",
    "UX",
    "UI",
    "user experience",
    "product design",
    "graphic",
    "typography",
    "branding",
    "NID",
    "NIFT",
    "fashion",
    "creative",
    "illustration",
    "motion",
    "Figma",
    "Sketch",
    "Adobe",
    "prototype",
    "usability",
    "interface",
  ],
  Biotech: [
    "biotech",
    "biotechnology",
    "pharma",
    "pharmaceutical",
    "drug",
    "genomics",
    "gene",
    "CRISPR",
    "vaccine",
    "clinical",
    "biology",
    "biochemistry",
    "laboratory",
    "research",
    "cancer",
    "healthcare",
    "medtech",
    "bioinformatics",
    "protein",
    "cell",
    "DNA",
  ],
};

export const INDIAN_CITIES: string[] = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Amritsar",
  "Chandigarh",
  "Patiala",
  "Ludhiana",
  "Surat",
  "Kochi",
  "Coimbatore",
  "Indore",
  "Bhopal",
  "Nagpur",
  "Visakhapatnam",
  "Vadodara",
  "Nashik",
  "Patna",
  "Bhubaneswar",
  "Guwahati",
  "Thiruvananthapuram",
  "Raipur",
  "Ranchi",
  "Dehradun",
  "Jodhpur",
  "Agra",
  "Varanasi",
  "Meerut",
  "Faridabad",
  "Gurugram",
  "Noida",
  "Ghaziabad",
  "Mysuru",
  "Mangaluru",
  "Hubli",
  "Tiruchirappalli",
  "Madurai",
  "Vijayawada",
  "Guntur",
  "Jabalpur",
  "Gwalior",
  "Srinagar",
  "Shimla",
  "Jalandhar",
];

export interface TagResult {
  branch_tags: string[];
  city_tags: string[];
}

/**
 * Tags an article by matching keywords against title + first 200 chars of body.
 * All matching is case-insensitive.
 */
export function tagArticle(title: string, body: string): TagResult {
  const haystack = (title + " " + body.slice(0, 200)).toLowerCase();

  const branch_tags: string[] = [];
  for (const [branch, keywords] of Object.entries(BRANCH_KEYWORDS)) {
    for (const kw of keywords) {
      if (haystack.includes(kw.toLowerCase())) {
        branch_tags.push(branch);
        break;
      }
    }
  }

  const city_tags: string[] = [];
  for (const city of INDIAN_CITIES) {
    if (haystack.includes(city.toLowerCase())) {
      city_tags.push(city);
    }
  }

  return { branch_tags, city_tags };
}
